### ISSUE TITLE
NetDns2 Library is missing file Header.php

### ISSUE THREAD

**Issue by sjbartley** [cubiclesoft/sso-server#1]
File Header.php is missing from /support/Net/DNS2

As per https://github.com/mikepultz/netdns2/tree/master/Net/DNS2 you can see the file Header.php is meant to be included. This breaks the sign-up process (and possibly other issues). 

The fix: file .gitignore is ignoring header.php files everywhere - but this needs to be only in the root.

Comparing with the current version of NetDns2, I can see the files cdnskey.php, csync.php and openpgpkey.php are missing from /support/Net/DNS2/RR but this may just be a different version.

So, I think the .gitignore needs to be:
/admin_hook.php
/config.php
/header.php
/footer.php
/index__.php
/settings.php
/support/_.mmdb

Thanks for the great work :)

**Comment by cubiclesoft** [comment]
Should be fixed now.

As a side note as mentioned in the README for this repo, this repo isn't really meant for direct use.  It's the interim location prior to releases and for development purposes.  Always use the official releases on production servers.
