### ISSUE TITLE
sso-server combine with ldap

### ISSUE THREAD

**Issue by janice0324** [cubiclesoft/sso-server#10]
Can you provide some tutorial or documents about combine with LDAP,  thanks
By the way, when I click enable of ldap, it shows "The ldap_connect() function does not exist. LDAP won't work until the LDAP PHP extension is enabled."

**Comment by cubiclesoft** [comment]
You need to install the PHP LDAP extension on your host.  For example, on Ubuntu that might be:

`sudo apt install php-ldap`

Once you get the PHP extension installed, the LDAP provider itself is pretty self-explanatory.  However, I will admit that I am assuming that you know enough about LDAP/AD to know how to fill in the fields.  Plus it has a debugging mode that you can turn on.  I've only ever had one complaint about the LDAP integration but they were running a fairly complex AD setup.
