### ISSUE TITLE
installation problem(php version)

### ISSUE THREAD

**Issue by janice0324** [cubiclesoft/sso-server#11]
When installed server and client, I test it on "test_flat.php" , and the result shows "**Unable to obtain SSO server login access. Error: Unable to decode response data from the serve**r", is it the problem that lack of mcrypt_module_open in my php .

by the way, the version of my php is 5.3.3，is it necessary to upgrade to 5.4

thaks

**Comment by cubiclesoft** [comment]
Check your web server error log or dump the data returned from the client with `var_dump()` in [support/sso_functions.php](https://github.com/cubiclesoft/sso-client-php/blob/master/support/sso_functions.php#L119) around line 119 before it attempts to decode the response.  More than likely the server is emitting a PHP notice/warning/error message.  If you are missing a function, then you probably need to add the relevant extension.

I see you got the LDAP issue worked out.

The minimum version of PHP that I officially support is what is shown on the [php.net](https://php.net/) homepage right rail.  Your versions are technically unsupported and likely have numerous security vulnerabilities (just look at [the PHP 5.x changelog](https://www.php.net/ChangeLog-5.php#5.3.29) - you are at least 26 releases behind the latest 5.3 and 5.3.29 was the last official release).  Unless you are manually patching and building PHP every time a new vulnerability is discovered in newer PHP, then your version is quite out of date.  Official upstream support for PHP 5.x was dropped in the last couple of months.  A number of distros still deploy 5.6 but not for much longer.  Everyone should be running at least PHP 7.1.x.  I generally run the latest PHP after the .4 point release (i.e. 7.3.4 is when I'll start migrating over to 7.3, which means I'm running 7.2.16 right now).  Unofficially, I try to support whatever I can, within reason, but 5.3.3 was released almost 9 years ago and the language has changed a bit in the interim.

**Comment by cubiclesoft** [comment]
Closing this issue.
