### ISSUE TITLE
access_token=?

### ISSUE THREAD

**Issue by wh1337** [cubiclesoft/sso-server#12]
I'm not sure where I can get the access_token parameter from? I'm trying to connect the SSO generic login portion to Kanboard, however it always comes up as 'external authentication failed' I feel like the reason is because on my User section, I do not have the access_token parameter listed, but I have no idea where to even go to get the access_token parameter at in the admin panel on the sso server. Can you help me?

Thank you!!

**Comment by cubiclesoft** [comment]
It's probably wanting the OAuth2 URL + `?access_token=` on the end of the URL.

For example:

`https://yourdomain.com/sso/oauth2/?access_token=`

Or, more accurately, the software is probably looking for an equals sign on the end of a URL that it can plop an access token onto.

This is the most annoying aspect of OAuth2:  The designers created a mostly-elegant, strictly-defined specification and then, right as they are about to cross the finish line, they manage to snatch defeat from the jaws of victory.  They inexplicably decided to drop the ball and let people name their access tokens - which happen to be the most important part of the equation - whatever the OAuth2 implementer wants to name them.  Most people, like me, sanely decide to use the string 'access_token' in the URL but not everyone does (e.g. LinkedIn uses 'oauth2_access_token').
