### ISSUE TITLE
Problem on creating account

### ISSUE THREAD

**Issue by wilfriedcoffiea** [cubiclesoft/sso-server#13]
Thank you again for your great work!

I think I have correctly configured the system but I get this error when I try to create a user in Generic Login : *Invalid e-mail address. Invalid domain name. Internal exception occurred.*
![screencapture](https://user-images.githubusercontent.com/20947891/66331238-95ec6180-e921-11e9-9313-c0c25b8f6d16.png)

Please could you help me?

**Comment by cubiclesoft** [comment]
That exception is occurring in the Net::DNS2 library while validating the domain portion of the email address in `support/smtp.php` against DNS.

Look for this line of code in `support/smtp.php` (around line 1809):

```php
return array("success" => false, "error" => self::SMTP_Translate("Invalid domain name.  Internal exception occurred."), "errorcode" => "dns_library_exception", "info" => self::SMTP_Translate("%s (%s).", $e->getMessage(), $domain));
```

You could try putting a `var_dump($e->getMessage());  exit();` right before that line of code to see what the actual error is.

My guess is that you are running into Google DNS related issues from your host.  If that is the case, then I don't see an easy fix (e.g. a configuration item) that doesn't break upgrade paths for you.  A simple fix could be to replace `8.8.8.8` and `8.8.4.4` in the same file with known good DNS servers but you would have to remember to apply the same change every time you upgrade the SSO server software.

**Comment by wilfriedcoffiea** [comment]
Thank you for your reply.

When I put this code `var_dump($e->getMessage()); exit();` I get this message:
`string(24) "timeout on read select()"`

The first time this exception occurred I didn't set up SMTP/POP3 as it is optional.

Right now I try to set up it and this what I get.
![screencapture-accounts-sanlamconnect-install-php-2019-10-11-10_42_53](https://user-images.githubusercontent.com/20947891/66645991-6638a480-ec14-11e9-96eb-86eb9c001b53.png)

**Comment by wilfriedcoffiea** [comment]
I also want to signify something: The system installs successfully on several other servers. 
By against a just new server "cloudweb3" hosted at OVH I encounter this difficulty.
If this information can help to diagnose the problem.

**Comment by cubiclesoft** [comment]
DNS is timing out for you.  More specifically, OVH is blocking outbound network requests to Google DNS servers on their network for some, but not all, VPS and cloud systems.  SSH into your system and `ping 8.8.8.8` and `ping 8.8.4.4`.  You can also try nslookup with those servers.  If ping and nslookup are timing out, then OVH or the host is dropping all traffic to the IP, including ICMP echo requests, and that's the source of the problem.

I've got an idea on how to fix it for SSO server.

**Comment by cubiclesoft** [comment]
Try the latest version.  The installer won't work but the settings can configure DNS servers now.  The Configuration section also attempts to detect DNS server configuration for the host to make it easy to copy and paste the IP addresses into the main box.

![AddedDNSServersOption](https://user-images.githubusercontent.com/1432111/66707248-42e42700-ecf2-11e9-91e2-73b4510a209e.png)

**Comment by wilfriedcoffiea** [comment]
This is what I get when I try the latest version:
 
Please correct the following problem:
`Unable to send verification e-mail. Expected a 250 response from the SMTP server upon MAIL FROM.`

I didn’t receive confirmation e-mail when signup new account but it has been created. And all things works well on the system.
It just remains to fix the problem of sending emails

**Comment by cubiclesoft** [comment]
Your configured email server responded with something other than a 250 response while trying to send the `MAIL FROM` command.  On the upside, DNS is now apparently working properly for you and SSO server is connecting to the SMTP server and getting somewhere with it before the SMTP server drops the request.

In `providers/sso_login/index.php`, approximately line 1754:

```php
	$result = SSO_SendEmail($fromaddr, $email, $subject, $htmlmsg, $textmsg);
```

Temporarily add:

```php
if ($_SERVER["REMOTE_ADDR"] === "your.ip.address.here")  // <-- Put your public IP address here.
{
  echo "<pre>";
  var_dump($result);
  exit();
}
```

After that line and try sending the verification email again.  It should dump more information out about the specific response from the SMTP server.

If you want the full byte-for-byte conversation between your host and the SMTP server, also temporarily modify `support/sso_functions.php`, approximately line 879:

```php
		$smtpoptions = array(
"debug" => true,  // <-- Add this line.
			"headers" => $headers,
			"htmlmessage" => $htmlmsg,
			"textmessage" => $textmsg,
			"server" => SSO_SMTP_SERVER,
			"port" => SSO_SMTP_PORT,
			"secure" => (SSO_SMTP_PORT == 465),
			"username" => SSO_SMTPPOP3_USER,
			"password" => SSO_SMTPPOP3_PASS,
			"nameservers" => SSO_GetDNSServers()
		);
```

Dumping debug information may expose sensitive information as plain text (e.g. your SMTP/POP3 server password).  Hence the reason for the IP address check.

Note:  I don't recommend GMail for sending messages except for testing purposes only.  GMail doesn't like being an email relay for more than a few messages.  Installing Postfix somewhere (and setting up an appropriate SPF record) and configuring the SSO server to point at the Postfix installation is usually a better solution.  GMail also has other problems, including IPv6 issues.

Email is hard to get working.  It's anything that sends email, not just SSO server.

**Comment by wilfriedcoffiea** [comment]
I tried it on another server and everything works like a charm. But on the previous server I don't have good results. Then I decide to continue on this server and leave the first one for another project. Thank you for your help.

**Comment by cubiclesoft** [comment]
You're welcome.
