### ISSUE TITLE
Facebook auth

### ISSUE THREAD

**Issue by VladHrytsev** [cubiclesoft/sso-server#15]
Hi
Auth by Facebook doesn't work :(
I add callback url for my facebook application but SSO Server set 'redirect_url' as url with GET params like 'state', 'sos_provider', 'sos_facebook_action', etc...
Facebook not support callback url with GET params and say that redirect url not in 'white list'

Facebook API v2.2
Generated url by SSO Server:
https://www.facebook.com/v2.2/dialog/oauth?client_id=[app_id]&redirect_uri=[url]%2F%3Fsso_provider%3Dsso_facebook%26sso_facebook_action%3Dsignin&state=iqVTI8msHFSYgtIovR6HLhmmYUnQewC0&scope=email
In Facebook application I add [url] to white list

**Comment by cubiclesoft** [comment]
Add the GET params from the `redirect_uri` to your Facebook app.

**Comment by VladHrytsev** [comment]
But I can't do this. In `redirect_uri` I have `state` param. `state` param is dynamic param. If i add `redirect_uri` to application FB get me message about white list

**Comment by cubiclesoft** [comment]
In your example, `state` is sent separately in the URL.

In your Facebook app's whitelist, you want:

`https://yourdomain.com/sso/server/?sso_provider=sso_facebook&sso_facebook_action=signin`

Not:

`https://yourdomain.com/sso/server/`

Facebook is complaining about not having the `?sso_provider=sso_facebook&sso_facebook_action=signin` portion of the URL in the approved URLs list.  They are being strict about what they accept.  It'll work.

The `state` is supposed to be dynamic.  It's part of the OAuth2 specification for confirming the return response originated from the SSO server.  Facebook will pass it back after the user approves the application.

**Comment by VladHrytsev** [comment]
The reason of issue was that the FB does not accept GET parameters on the root path.
And I was not attentive to state in GET parameters, thank you.

So, FB **can't accept** something like this: `https://yourdomain.com/?sso_provider=sso_facebook&sso_facebook_action=signin`

But FB **accept** this: `https://yourdomain.com/sso/server/?sso_provider=sso_facebook&sso_facebook_action=signin`

**Comment by cubiclesoft** [comment]
Huh.  That seems like a weird bug/limitation.  I would normally suggest talking to Facebook about a bug in their software, but that's the equivalent of telling someone to go talk to a brick wall - the results would be approximately the same.

Their system might accept this format instead:

`https://yourdomain.com/index.php?sso_provider=sso_facebook&sso_facebook_action=signin`

That's _slightly_ off the root but not in a subdirectory.
