### ISSUE TITLE
Redirect Loop

### ISSUE THREAD

**Issue by maksym-prikhodko** [cubiclesoft/sso-server#16]
when I'm use proxy Cloudflare and SSL protection on Cloudflare at install sso-server the Over  SSL option in check requirements is "red" - NO, but web site is loading over SSL  

I think need add the additional check for HTTP_X_FORWARDED_PROTO to the function BB_IsSSLRequest()
if ($_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {
    $_SERVER['https'] = 'on';
}

**Comment by cubiclesoft** [comment]
Your backend is NOT SSL.  That means between Cloudflare and your server, there is no encryption.  Anyone on the wire between the two hosts can intercept and modify THOSE packets.  The SSO client does its own encryption on a per-API key basis, but that's a separate thing.

HTTP headers can be spoofed.  Changing that function in the way you suggest opens up a serious security hole.  The correct solution is to set up SSL between Cloudflare and your backend.

https://support.cloudflare.com/hc/en-us/articles/200170416-End-to-end-HTTPS-with-Cloudflare-Part-3-SSL-options

**Comment by maksym-prikhodko** [comment]
Thank You
