### ISSUE TITLE
Parse error: syntax error, unexpected '.0' (T_DNUMBER) in admin_hook.php

### ISSUE THREAD

**Issue by maksym-prikhodko** [cubiclesoft/sso-server#18]
When I've Install the SSO-Server in admin_hook.php missed the " ' " -> example

`<?php
	if (!defined("SSO_FILE"))  exit();

	if ($_SERVER["REMOTE_ADDR"] !== 172.30.0.3)  exit();

	$bb_usertoken = f43d41cd7cd3413fb8f979d81fc65f4a;
	$sso_site_admin = true;
`

**Comment by cubiclesoft** [comment]
Whoops.  Fixed.

**Comment by maksym-prikhodko** [comment]
Thank You
