### ISSUE TITLE
Sorry to bother again :)

### ISSUE THREAD

**Issue by FlurryNight** [cubiclesoft/sso-server#22]

**Comment by cubiclesoft** [comment]
The OAuth2 client library you are using appears to only support Bearer token HTTP Authorization headers.

I've applied a patch to the SSO server's OAuth2 shim (oauth2/index.php) and updated the documentation.  Once you update to the latest SSO server, you shouldn't need `?access_token=` in the resource URL for the client library you are using.

**Comment by FlurryNight** [comment]
> The OAuth2 client library you are using appears to only support Bearer token HTTP Authorization headers.
> 
> I've applied a patch to the SSO server's OAuth2 shim (oauth2/index.php) and updated the documentation.  Once you update to the latest SSO server, you shouldn't need `?access_token=` in the resource URL for the client library you are using.

Oh ok, thanks for your quick response and attention

Best regards

**Comment by ZR3SYSTEMS** [comment]
It works, i had to do some changes (maybe related to reverse proxy )

`
$headers = apache_request_headers(); //needed this
		//var_dump($headers['Authorization']);
		// Set 'access_token' to be the Bearer token when the header exists.
		if (isset($headers["Authorization"]) && is_string($headers["Authorization"]) && strncasecmp($headers["Authorization"], "Bearer ", 7) == 0)
		{
			$_REQUEST["access_token"] = trim(substr($headers["Authorization"], 7));
			//echo trim(substr($_SERVER["HTTP_AUTHORIZATION"], 7));
		}
`

It works like a charm! 

![err](https://user-images.githubusercontent.com/47457170/78777728-fc664100-7991-11ea-93ce-5f9b4c105c2d.png)


now i will wrap this in a beautiful json output :)

**Comment by cubiclesoft** [comment]
Aw nuts.  Looks like Apache only passes on valid 'Basic' Authorization headers to PHP via the `$_SERVER` variable.  IMO, Apache is broken in a few key modern areas (WebSocket and custom protocol support like WebRoute, handling Bearer tokens, etc).  Should be fixed now.

I also updated the docs to reflect an alternate solution via `SetEnvIf`.

Modifying the SSO server code means you'll make future upgrades/updates harder on yourself.

By the way, when you post code snippets on GitHub, you should surround the code with three backticks at the start and end and optionally the first set of backticks with the language being used (`php` in this case).  Single backticks are for inline code while triple backticks are for blocks of code.

**Comment by ZR3SYSTEMS** [comment]
Ok,thanks for the tip, 

U noticed the amounts of edits ? 😂

Im newbie to github ahah
