### ISSUE TITLE
OAuth2 System

### ISSUE THREAD

**Issue by felischmi2003** [cubiclesoft/sso-server#27]
I have some questions....
Can i build a OAuth2 Server Like Google, Facebook?
With edit-profile, profile-picture and Developer-Site?
And Redirect url from server back to site is?

Please Answer

Felix Schmitt

**Comment by cubiclesoft** [comment]
Sure.  Read the documentation on the OAuth2 shim:

https://github.com/cubiclesoft/sso-server/blob/master/docs/integrating-with-third-party-software.md

To avoid confusion, it is a good idea to install the SSO server first before attempting to use the OAuth2 shim.

Closing this as this isn't an issue.  Please only open issues for bugs in the software and use Discord for questions.  Thanks.
