### ISSUE TITLE
Admin Panel after a short time not Working

### ISSUE THREAD

**Issue by felischmi2003** [cubiclesoft/sso-server#29]
Hello, 
I have the Script uploading above the Server.
I installed this Step by Step.
Than works the Admin Panel.
After a short time, when i reload the site,than whiteb screen.
are the API is Working. This Problem had I the last 24 h ever!
After ever new Installation!

I hosted the Script above a Plesk Windows Server, and have all permissions.

Please help me everyone!
With best regrades,
Felix Schmitt

(P.s. Sorry for my englisch, i come from germany)

**Comment by cubiclesoft** [comment]
Check the Network tab in Developer Tools in your web browser.  What HTTP code is the request for the page returning?

Check your server access and error logs.  Is there a specific error message being emitted?

I can't really think of anything to cause the issue you describe to appear after 24 hours.  I've been running the server for years without issue.

**Comment by felischmi2003** [comment]
Thanks for answer,
i have looked in the DevTools, Status Code 200, OK.
this have no design output. 
and the admin.php have no space.

**Comment by cubiclesoft** [comment]
Please check your server/website logs for PHP error/warning messages.

I only run on Linux VPS providers (e.g. OVH, DigitalOcean, AWS) but do develop locally on Windows + Apache.  IIS support is largely untested.

**Comment by felischmi2003** [comment]
Hello, 
sorry I had last week no time for my Site .

I have looked in the Logfiles, no errors.
Ever output code: 200 OK

**Comment by cubiclesoft** [comment]
If you are using 'index_hook.php' or 'admin_hook.php' with an IP address and your public IP address changes, then maybe it is just calling `exit();` without doing anything.

**Comment by felischmi2003** [comment]
Ich have find the Problem in Developertools. 
Sorry this is in German:


`Das Cookie “pmaCookieVer” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/admin.php?action=config&provider=sso_login&action2=config&sec_t=8b77e9a85b1a3d308a80f64947cdef6da31f51d7&sec_extra=provider,action2” behandelt, da das Schema nicht übereinstimmt. admin.php
Das Cookie “pma_lang” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/admin.php?action=config&provider=sso_login&action2=config&sec_t=8b77e9a85b1a3d308a80f64947cdef6da31f51d7&sec_extra=provider,action2” behandelt, da das Schema nicht übereinstimmt. admin.php
Das Cookie “pma_collation_connection” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/admin.php?action=config&provider=sso_login&action2=config&sec_t=8b77e9a85b1a3d308a80f64947cdef6da31f51d7&sec_extra=provider,action2” behandelt, da das Schema nicht übereinstimmt. admin.php
Das Cookie “pma_console_height” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/admin.php?action=config&provider=sso_login&action2=config&sec_t=8b77e9a85b1a3d308a80f64947cdef6da31f51d7&sec_extra=provider,action2” behandelt, da das Schema nicht übereinstimmt. admin.php
Das Cookie “pmaCookieVer” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/admin.php?action=config&provider=sso_login&action2=config&sec_t=8b77e9a85b1a3d308a80f64947cdef6da31f51d7&sec_extra=provider,action2” behandelt, da das Schema nicht übereinstimmt. admin.php
Das Cookie “pma_lang” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/admin.php?action=config&provider=sso_login&action2=config&sec_t=8b77e9a85b1a3d308a80f64947cdef6da31f51d7&sec_extra=provider,action2” behandelt, da das Schema nicht übereinstimmt. admin.php
Das Cookie “pma_collation_connection” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/admin.php?action=config&provider=sso_login&action2=config&sec_t=8b77e9a85b1a3d308a80f64947cdef6da31f51d7&sec_extra=provider,action2” behandelt, da das Schema nicht übereinstimmt. admin.php
Das Cookie “pma_console_height” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/admin.php?action=config&provider=sso_login&action2=config&sec_t=8b77e9a85b1a3d308a80f64947cdef6da31f51d7&sec_extra=provider,action2” behandelt, da das Schema nicht übereinstimmt. admin.php
Das Cookie “pmaCookieVer” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/support/admin.css” behandelt, da das Schema nicht übereinstimmt. admin.css
Das Cookie “pma_lang” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/support/admin.css” behandelt, da das Schema nicht übereinstimmt. admin.css
Das Cookie “pma_collation_connection” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/support/admin.css” behandelt, da das Schema nicht übereinstimmt. admin.css
Das Cookie “pma_console_height” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/support/admin.css” behandelt, da das Schema nicht übereinstimmt. admin.css
Das Cookie “pmaCookieVer” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/support/admin_print.css” behandelt, da das Schema nicht übereinstimmt. admin_print.css
Das Cookie “pma_lang” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/support/admin_print.css” behandelt, da das Schema nicht übereinstimmt. admin_print.css
Das Cookie “pma_collation_connection” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/support/admin_print.css” behandelt, da das Schema nicht übereinstimmt. admin_print.css
Das Cookie “pma_console_height” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/support/admin_print.css” behandelt, da das Schema nicht übereinstimmt. admin_print.css
Das Cookie “pmaCookieVer” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/support/jquery-1.11.0.min.js” behandelt, da das Schema nicht übereinstimmt. jquery-1.11.0.min.js
Das Cookie “pma_lang” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/support/jquery-1.11.0.min.js” behandelt, da das Schema nicht übereinstimmt. jquery-1.11.0.min.js
Das Cookie “pma_collation_connection” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/support/jquery-1.11.0.min.js” behandelt, da das Schema nicht übereinstimmt. jquery-1.11.0.min.js
Das Cookie “pma_console_height” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/support/jquery-1.11.0.min.js” behandelt, da das Schema nicht übereinstimmt. jquery-1.11.0.min.js
Das Cookie “pmaCookieVer” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/support/admin.js” behandelt, da das Schema nicht übereinstimmt. admin.js
Das Cookie “pma_lang” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/support/admin.js” behandelt, da das Schema nicht übereinstimmt. admin.js
Das Cookie “pma_collation_connection” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/support/admin.js” behandelt, da das Schema nicht übereinstimmt. admin.js
Das Cookie “pma_console_height” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/support/admin.js” behandelt, da das Schema nicht übereinstimmt. admin.js
Das Cookie “pmaCookieVer” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/support/jquery_ui_themes/smoothness/jquery-ui-1.10.4.css” behandelt, da das Schema nicht übereinstimmt. jquery-ui-1.10.4.css
Das Cookie “pma_lang” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/support/jquery_ui_themes/smoothness/jquery-ui-1.10.4.css” behandelt, da das Schema nicht übereinstimmt. jquery-ui-1.10.4.css
Das Cookie “pma_collation_connection” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/support/jquery_ui_themes/smoothness/jquery-ui-1.10.4.css” behandelt, da das Schema nicht übereinstimmt. jquery-ui-1.10.4.css
Das Cookie “pma_console_height” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/support/jquery_ui_themes/smoothness/jquery-ui-1.10.4.css” behandelt, da das Schema nicht übereinstimmt. jquery-ui-1.10.4.css
Das Cookie “pmaCookieVer” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/support/jquery-ui-1.10.4.min.js” behandelt, da das Schema nicht übereinstimmt. jquery-ui-1.10.4.min.js
Das Cookie “pma_lang” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/support/jquery-ui-1.10.4.min.js” behandelt, da das Schema nicht übereinstimmt. jquery-ui-1.10.4.min.js
Das Cookie “pma_collation_connection” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/support/jquery-ui-1.10.4.min.js” behandelt, da das Schema nicht übereinstimmt. jquery-ui-1.10.4.min.js
Das Cookie “pma_console_height” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/support/jquery-ui-1.10.4.min.js” behandelt, da das Schema nicht übereinstimmt. jquery-ui-1.10.4.min.js
Das Cookie “pmaCookieVer” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/favicon.ico” behandelt, da das Schema nicht übereinstimmt. favicon.ico
Das Cookie “pma_lang” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/favicon.ico” behandelt, da das Schema nicht übereinstimmt. favicon.ico
Das Cookie “pma_collation_connection” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/favicon.ico” behandelt, da das Schema nicht übereinstimmt. favicon.ico
Das Cookie “pma_console_height” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/favicon.ico” behandelt, da das Schema nicht übereinstimmt. favicon.ico
Das Cookie “pmaCookieVer” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/support/admin.css” behandelt, da das Schema nicht übereinstimmt. admin.css
Das Cookie “pma_lang” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/support/admin.css” behandelt, da das Schema nicht übereinstimmt. admin.css
Das Cookie “pma_collation_connection” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/support/admin.css” behandelt, da das Schema nicht übereinstimmt. admin.css
Das Cookie “pma_console_height” wird bald als Cross-Site-Cookie gegen “https://accounts.edingmc.com/support/admin.css” behandelt, da das Schema nicht übereinstimmt. admin.css
`

**Comment by felischmi2003** [comment]
Thanks for your time.

I've had hostet on an Plesk Server, no an Single Server without Plesk now is working.

I have another questions (own design), i start a new issue for this.

With best reguards,
Felix Schmitt
