### ISSUE TITLE
Own Form design.

### ISSUE THREAD

**Issue by felischmi2003** [cubiclesoft/sso-server#30]
### **THIS IS NOT A ISSUE**

I've a Question,
i will design my own Form, i have designed the form site, but i don't know design the form elements.

i have read all files of this Script, but I nothing found.

Sorry for my english.

With best regards,
Felix Schmitt

**Comment by cubiclesoft** [comment]
If you are referring to Generic Login, the forms are hardcoded in the system.  You can style the existing forms by applying CSS in your custom header/footer.

If you are referring to adding a login form on your website, don't do that.  Defer all login to the SSO server.  That's what it is there for.
