### ISSUE TITLE
Own language

### ISSUE THREAD

**Issue by felischmi2003** [cubiclesoft/sso-server#32]
I've seen in the code, BBCodeTranslation.
How can I do translate thescripts? 
I don't found anything in the docs.
Please help, thanks

Best regrats,
Felix Schmitt

**Comment by cubiclesoft** [comment]
The core translation function is `BB_Translate()`.  It intakes a string and attempts to find a matching string in the loaded language map.

Language mappings are a PHP array usually stored in `lang/IANA-LANG/index.php`.  The IANA language for German is 'de', so the language path should be `lang/de/index.php`.

```php
<?php
  $bb_langmap["de"] = array(
    "Return to the application" => "Zurück zur Anwendung",  // <-- I Google Translated that text...obviously not a good solution.
  );
```

If you define a function called `BB_Untranslated($args)` in your file, you can capture untranslated strings by writing them to disk somewhere.

**Comment by felischmi2003** [comment]
Thanks
