### ISSUE TITLE
Security Issue - Generic Login - Native PHP Bcrypt hashing

### ISSUE THREAD

**Issue by tateu** [cubiclesoft/sso-server#34]
Using Generic Login with Native PHP Bcrypt hashing and a combined length of a username and email address that totals 37 or more characters, I am able to login with any password I choose.

This is because PHP truncates the password to a max of 72 characters.

https://www.php.net/manual/en/function.password-hash.php

> Using the PASSWORD_BCRYPT as the algorithm, will result in the password parameter being truncated to a maximum length of 72 bytes.

from index.php in sso_login, the password is created from a combination of 4 elements

```
$data = $username . ":" . $email . ":" . $salt . ":" . $phrase;
$passwordinfo = self::HashPasswordInfo($data, $sso_settings["sso_login"]["password_mode"], $sso_settings["sso_login"]["password_minrounds"]);
```

So, if I have
```
username: very_long_username
email: very_long_email@example.net
salt: vyZFOrJvunsk3ofUhDSsKQAuXYSULvKM
password: chutnee stereographes ruddiest mesnalties
```

the password hash is created from:
`very_long_username:very_long_email@example.net:vyZFOrJvunsk3ofUhDSsKQAuXYSULvKM:chutnee stereographes ruddiest mesnalties`

When truncated to the PHP max of 72 characters, you get:
`very_long_username:very_long_email@example.net:vyZFOrJvunsk3ofUhDSsKQAuX`

which does not include the full salt and does not include any of the password, thus allowing me to login using any password I choose.

This issue does not appear to be present when using using Blowfish::Hash().

**Comment by cubiclesoft** [comment]
Oh well that's just fantastic.  Sigh.  I don't believe that information was in the PHP documentation when I first added `password_hash()` functionality.  Also, that's a fairly bad limitation to have in PHP.

I've committed a fix for this issue.  Try it again.

Relevant:  https://youtu.be/g9XrrEaZ7Y4?t=145

**Comment by tateu** [comment]
Not quite.  You also need the same line added to the VerifyPasswordInfo function.

```
if (strlen($data) > 72) $data = hash("sha256", $data, true);

$result = @password_verify($data, pack("H*", $hash));
```

I'm not sure of an easy way around it but this will break any existing Bcrypt Generic logins that fall into the greater than 72 character limit.  Anyone with this issue will have to run through the account recovery process to change their password so it gets rehashed using the sha256 hash method and written to the database.

**Comment by cubiclesoft** [comment]
Okay.  Now it should be fixed.  I've been so busy lately working on the latest project trying to get it out the door.

**Comment by tateu** [comment]
Yes, that does it.  Thanks.
