### ISSUE TITLE
Not able to move SSO easily

### ISSUE THREAD

**Issue by QueenLinux** [cubiclesoft/sso-server#4]
So, going through the process of migrating a dev copy to another server for deployment, changing configs, all that, I get an error when attempting to access the system.

Unable to obtain SSO server login access. Error: Unable to decode response data from the server.

I've looked in the functions, and found where it references this error.
Please advise

**Comment by cubiclesoft** [comment]
If you didn't use the SSO server installer to install the product, then it could be anything.  The data sent to the server by the client is pre-encrypted (even over HTTPS endpoints) and the response is usually encrypted too.

I'd start by adding `var_dump($result)` in the client's `support/sso_functions.php` file right before the `exit()` statement.  `$result` contains the body of the response from the server.  The client is successfully making a request and getting a valid HTTP response.  You just don't know what that is (yet) and whatever the output is will likely reveal the real issue.

Issue trackers are not the correct place for getting help.  Please use the forums.  Thanks.
